# from core.exceptions import ErrorCode as CoreErrorCode
# from exceptions import CustomException


# class ErrorCode(CoreErrorCode):
#     pass
